# Generated by Django 2.2.12 on 2020-07-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialParking',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('slot_no', models.IntegerField(unique=True)),
                ('number_plate', models.CharField(blank=True, max_length=15, null=True)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('image', models.BinaryField(editable=True)),
            ],
            options={
                'db_table': 'commercial_parking',
                'managed': False,
            },
        ),
    ]
