# Generated by Django 2.2.12 on 2020-07-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialparking',
            options={},
        ),
    ]
