# Generated by Django 2.2.12 on 2020-07-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_detect', '0002_auto_20200719_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.IntegerField(blank=True, null=True)),
                ('number_plate', models.CharField(blank=True, max_length=15, null=True)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commercial_history',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='commercialparking',
            name='image',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
