# Generated by Django 2.2.12 on 2020-07-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_detect', '0003_auto_20200727_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialhistory',
            options={},
        ),
    ]
