# Generated by Django 2.2.12 on 2020-07-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_detect', '0004_auto_20200727_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialhistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='commercialparking',
            options={'managed': False},
        ),
    ]
