# Generated by Django 2.2.12 on 2020-07-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_detect', '0005_auto_20200727_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialhistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='commercialparking',
            options={},
        ),
    ]
