# Generated by Django 2.2.12 on 2020-07-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_detect', '0006_auto_20200727_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialhistory',
            options={'managed': False},
        ),
    ]
