# Generated by Django 2.2.12 on 2020-08-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_detect', '0007_auto_20200727_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('register_name', models.CharField(blank=True, max_length=15, null=True)),
                ('number_plate', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('alloted_slot', models.IntegerField(blank=True, null=True)),
                ('current_person_name', models.CharField(blank=True, max_length=15, null=True)),
                ('current_person_mobile_no', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'resident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('number_plate', models.CharField(blank=True, max_length=15, null=True)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('visitor_name', models.CharField(blank=True, max_length=30, null=True)),
                ('visitor_mob', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'visitor',
                'managed': False,
            },
        ),
    ]
