# Generated by Django 2.2.12 on 2020-08-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_detect', '0008_resident_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercialhistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={},
        ),
    ]
